//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShaderGenerator.Config {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShaderProfiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShaderProfiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShaderGenerator.Config.ShaderProfiles", typeof(ShaderProfiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute Shader Model 4.0.
        /// </summary>
        internal static string cs_4_0 {
            get {
                return ResourceManager.GetString("cs_4_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute Shader Model 4.1.
        /// </summary>
        internal static string cs_4_1 {
            get {
                return ResourceManager.GetString("cs_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute Shader Model 5.0.
        /// </summary>
        internal static string cs_5_0 {
            get {
                return ResourceManager.GetString("cs_5_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Shader Model 5.0.
        /// </summary>
        internal static string ds_5_0 {
            get {
                return ResourceManager.GetString("ds_5_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect Model 2.0.
        /// </summary>
        internal static string fx_2_0 {
            get {
                return ResourceManager.GetString("fx_2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect Model 4.0.
        /// </summary>
        internal static string fx_4_0 {
            get {
                return ResourceManager.GetString("fx_4_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect Model 4.1.
        /// </summary>
        internal static string fx_4_1 {
            get {
                return ResourceManager.GetString("fx_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect Model 5.0.
        /// </summary>
        internal static string fx_5_0 {
            get {
                return ResourceManager.GetString("fx_5_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry Shader Model 4.0.
        /// </summary>
        internal static string gs_4_0 {
            get {
                return ResourceManager.GetString("gs_4_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry Shader Model 4.1.
        /// </summary>
        internal static string gs_4_1 {
            get {
                return ResourceManager.GetString("gs_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry Shader Model 5.0.
        /// </summary>
        internal static string gs_5_0 {
            get {
                return ResourceManager.GetString("gs_5_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hull Shader Model 5.0.
        /// </summary>
        internal static string hs_5_0 {
            get {
                return ResourceManager.GetString("hs_5_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel Shader Model 2.0.
        /// </summary>
        internal static string ps_2_0 {
            get {
                return ResourceManager.GetString("ps_2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel Shader Model 2.0 a.
        /// </summary>
        internal static string ps_2_a {
            get {
                return ResourceManager.GetString("ps_2_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel Shader Model 2.0 b.
        /// </summary>
        internal static string ps_2_b {
            get {
                return ResourceManager.GetString("ps_2_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel Shader Model 2.0 (Software).
        /// </summary>
        internal static string ps_2_sw {
            get {
                return ResourceManager.GetString("ps_2_sw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel Shader Model 3.0.
        /// </summary>
        internal static string ps_3_0 {
            get {
                return ResourceManager.GetString("ps_3_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel Shader Model 3.0 (Software).
        /// </summary>
        internal static string ps_3_sw {
            get {
                return ResourceManager.GetString("ps_3_sw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel Shader Model 4.0.
        /// </summary>
        internal static string ps_4_0 {
            get {
                return ResourceManager.GetString("ps_4_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel Shader Model 4.0 (Level 9.0).
        /// </summary>
        internal static string ps_4_0_level_9_0 {
            get {
                return ResourceManager.GetString("ps_4_0_level_9_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel Shader Model 4.0 (Level 9.1).
        /// </summary>
        internal static string ps_4_0_level_9_1 {
            get {
                return ResourceManager.GetString("ps_4_0_level_9_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel Shader Model 4.0 (Level 9.3).
        /// </summary>
        internal static string ps_4_0_level_9_3 {
            get {
                return ResourceManager.GetString("ps_4_0_level_9_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel Shader Model 4.1.
        /// </summary>
        internal static string ps_4_1 {
            get {
                return ResourceManager.GetString("ps_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixel Shader Model 5.0.
        /// </summary>
        internal static string ps_5_0 {
            get {
                return ResourceManager.GetString("ps_5_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture Shader Model 1.0 (Software).
        /// </summary>
        internal static string tx_1_0 {
            get {
                return ResourceManager.GetString("tx_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex Shader Model 1.1.
        /// </summary>
        internal static string vs_1_1 {
            get {
                return ResourceManager.GetString("vs_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex Shader Model 2.0.
        /// </summary>
        internal static string vs_2_0 {
            get {
                return ResourceManager.GetString("vs_2_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex Shader Model 2.0 a.
        /// </summary>
        internal static string vs_2_a {
            get {
                return ResourceManager.GetString("vs_2_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex Shader Model 2.0 (Software).
        /// </summary>
        internal static string vs_2_sw {
            get {
                return ResourceManager.GetString("vs_2_sw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex Shader Model 3.0.
        /// </summary>
        internal static string vs_3_0 {
            get {
                return ResourceManager.GetString("vs_3_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex Shader Model 3.0 (Software).
        /// </summary>
        internal static string vs_3_sw {
            get {
                return ResourceManager.GetString("vs_3_sw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex Shader Model 4.0.
        /// </summary>
        internal static string vs_4_0 {
            get {
                return ResourceManager.GetString("vs_4_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex Shader Model 4.0 (Level 9.0).
        /// </summary>
        internal static string vs_4_0_level_9_0 {
            get {
                return ResourceManager.GetString("vs_4_0_level_9_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex Shader Model 4.0 (Level 9.1).
        /// </summary>
        internal static string vs_4_0_level_9_1 {
            get {
                return ResourceManager.GetString("vs_4_0_level_9_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex Shader Model 4.0 (Level 9.3).
        /// </summary>
        internal static string vs_4_0_level_9_3 {
            get {
                return ResourceManager.GetString("vs_4_0_level_9_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex Shader Model 4.1.
        /// </summary>
        internal static string vs_4_1 {
            get {
                return ResourceManager.GetString("vs_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex Shader Model 5.0.
        /// </summary>
        internal static string vs_5_0 {
            get {
                return ResourceManager.GetString("vs_5_0", resourceCulture);
            }
        }
    }
}
