#pragma message("Compiling precompiled headers.\n")

#include "../BombastEngineStd.h"
#include "../Utilities/DDSTextureLoader.h"
#include "../Utilities/WICTextureLoader.h"
#include "../Utilities/rapidxml.hpp"
#include "../Utilities/String.h"
#include "../Utilities/types.h"
#include "../Utilities/Initialization.h"
#include "../Utilities/Math.h"
#include "../Utilities/Timer.h"
#include "../Graphics2D/TextureClass.h"
#include "../Graphics2D/FontClass.h"
#include "../Graphics3D/D3DClass.h"
#include "../Graphics3D/Geometry.h"
#include "../Graphics3D/GraphicsManager.h"
#include "../Graphics3D/Scene.h"
#include "../Actor/Actor.h"
#include "../Actor/ActorComponent.h"
#include "../Bombast/interfaces.h"
#include "../Debugging/Logger.h"
#include "../Debugging/DebugText.h"
#include "../Events/EventManager.h"
#include "../Game/ProcessManager.h"
#include "../Shading/ShaderManager.h"